version: '3.8'

services:
  frontend:
    image: frontend-dev
    container_name: frontend-dev 
    build: 
      dockerfile: dev.Dockerfile
      context: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: backend-dev
    container_name: backend-dev
    build: 
      dockerfile: dev.Dockerfile
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
