version: '3.8'

services:
  frontend:
    image: frontend
    container_name: frontend
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: backend
    container_name: backend
    build: 
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
